providers:
  - name: aws
    #    accounts: # Optional. if you want to assume role to multiple account and fetch data from them
    #      - role_arn: arn:aws:iam::966797507899:role/user
    #    regions: # Optional. if commented out assumes all regions
    #      - us-east-1
    #      - us-west-2
    resources: # You can comment resources your are not interested in for faster fetching.
      - name: autoscaling.launch_configurations
      - name: cloudtrail.trails
      - name: directconnect.gateways
      - name: ec2.customer_gateways
      - name: ec2.flow_logs
      - name: ec2.images
      - name: ec2.instances
      - name: ec2.internet_gateways
      - name: ec2.nat_gateways
      - name: ec2.network_acls
      - name: ec2.route_tables
      - name: ec2.security_groups
      - name: ec2.subnets
      - name: ec2.vpc_peering_connections
      - name: ec2.vpcs
      - name: ecs.clusters
      - name: efs.filesystems
      - name: elasticbeanstalk.environments
      - name: elbv2.load_balancers
      - name: emr.clusters
      - name: fsx.backups
      - name: iam.groups
      - name: iam.password_policies
      - name: iam.policies
      - name: iam.roles
      - name: iam.users
      - name: kms.keys
      - name: rds.certificates
      - name: rds.clusters
      - name: redshift.clusters
      - name: s3.buckets
